services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-pgsql-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${UI_USER}
      PGADMIN_DEFAULT_PASSWORD: ${UI_PASSWORD}
    ports:
      - ${EXTERNAL_ADMIN_PORT}:80

networks:
  postgres:
    driver: bridge


