# The expose tag will let you expose ports without publishing them to the host machine, 
# but they will be exposed to the containers networks.
# https://docs.docker.com/compose/compose-file/#expose
# The ports tag will be mapping the host port with the container port HOST:CONTAINER

services:
  pgsql:
    image: postgres:latest
    container_name: pgsql-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks:
      - internal
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      # HOST-PORT:CONTAINER-PORT
      - ${POSTGRES_PORT}:5432
    # volumes:
    #   - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-pgsql-${COMPOSE_PROJECT_NAME}
    links:
      - pgsql
    depends_on:
      - pgsql
    restart: unless-stopped
    networks:
      - internal
    environment:
      PGADMIN_DEFAULT_EMAIL: ${UI_USER}
      PGADMIN_DEFAULT_PASSWORD: ${UI_PASSWORD}
    ports:
      - ${EXTERNAL_ADMIN_PORT}:80
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
  sam-app:
    image: ekarpovs/sam-app-${IMAGE_ARCH}:${IMAGE_VER}
    container_name: sam-app-${COMPOSE_PROJECT_NAME}
    depends_on:
      - pgsql
    restart: always
    networks:
      - internal
    env_file:
      - ./.env
    ports:
      # HOST-PORT:CONTAINER-PORT
      - ${EXTERNAL_PORT}:${PORT}
    stdin_open: true
    tty: true

# Concatinate your user name with the "integration-"
networks:
 internal:
   driver: bridge

