# The expose tag will let you expose ports without publishing them to the host machine, 
# but they will be exposed to the containers networks.
# https://docs.docker.com/compose/compose-file/#expose
# The ports tag will be mapping the host port with the container port HOST:CONTAINER

services:
  sam-app:
    image: ekarpovs/sam-app-${IMAGE_ARCH}:${IMAGE_VER}
    container_name: sam-app-${COMPOSE_PROJECT_NAME}
    networks:
      - internal
    env_file:
      - ./.env
    ports:
      # HOST-PORT:CONTAINER-PORT
      - ${EXTERNAL_PORT}:${PORT}
    stdin_open: true
    tty: true

# Concatinate your user name with the "integration-"
networks:
 internal:
   driver: bridge

