# The expose tag will let you expose ports without publishing them to the host machine, 
# but they will be exposed to the containers networks.
# https://docs.docker.com/compose/compose-file/#expose
# The ports tag will be mapping the host port with the container port HOST:CONTAINER

services:
  db-micro-service:
    image: ekarpovs/data-broadcast-micro-service-${IMAGE_ARCH}:${IMAGE_VER}
    container_name: db-micro-service-${COMPOSE_PROJECT_NAME}
    networks:
      - integration-${COMPOSE_PROJECT_NAME}
    env_file:
      - ./.env
    ports:
      # HOST-PORT:CONTAINER-PORT
      - ${EXTERNAL_PORT}:${PORT}
    volumes:
      - ${HOST_LOGGER_PATH}:${DOCKER_LOGGER_PATH}
    stdin_open: true
    tty: true

# Change the suffics "evgeny" to your user name"
networks:
  integration-user-name:
    external: true

#  volumes:
#    static:

