services:
  pgsql:
    image: mysql/mysql-server:8.0.13
    container_name: mysql-dev-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks:
      - postgres
    environment:
      SQL_ROOT_USER: ${SQL_ROOT_USER}
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      # HOST-PORT:CONTAINER-PORT
      - ${MYSQL_PORT}:3306
    # volumes:
    #   - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-pgsql-dev-${COMPOSE_PROJECT_NAME}
    links:
      - pgsql
    depends_on:
      - pgsql
    restart: unless-stopped
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${UI_USER}
      PGADMIN_DEFAULT_PASSWORD: ${UI_PASSWORD}
    ports:
      - ${EXTERNAL_ADMIN_PORT}:80
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

# volumes:
#   local_pgdata:
#   pgadmin-data:
